apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64", "arm64"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot", "on-demand"]
      - key: kubernetes.io/os
        operator: In
        values: ["linux"]
      - key: karpenter.k8s.aws/instance-family  # AWS-specific, adjust for other clouds
        operator: In
        values: ["t3", "m5"]  # General-purpose instances
      nodeClassRef:
        name: default
      taints:
      - key: "workload"
        value: "event-driven"
        effect: "NoSchedule"
    limits:
      cpu: 2000  
      memory: 2000Gi
    disruption:
      consolidationPolicy: WhenUnderutilized
      consolidateAfter: 30s
      expireAfter: 720h
